version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: wow-postgres
    restart: always
    environment:
      POSTGRES_DB: wowmarket
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: wow-market-api
    depends_on:
      - postgres
    environment:
      DB_PASSWORD: postgres
      BLIZZARD_CLIENT_ID: ${BLIZZARD_CLIENT_ID}
      BLIZZARD_CLIENT_SECRET: ${BLIZZARD_CLIENT_SECRET}
    ports:
      - "8080:8080"

volumes:
  postgres_data:

