version: '3.9'

services:

  postgres:
    image: postgres:16
    container_name: wow-postgres
    restart: always
    environment:
      POSTGRES_DB: wowmarket
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wow-market-api
    depends_on:
      - postgres
    environment:
      DB_PASSWORD: postgres
      BLIZZARD_CLIENT_ID: ${BLIZZARD_CLIENT_ID}
      BLIZZARD_CLIENT_SECRET: ${BLIZZARD_CLIENT_SECRET}
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/wowmarket
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    ports:
      - "8080:8080"
    restart: on-failure

volumes:
  postgres_data:
