spring.application.name=wow-market

# ===============================
# DATABASE - PostgreSQL
# ===============================
spring.datasource.url=jdbc:postgresql://postgres:5432/wowmarket
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect


# ===============================
# SERVER
# ===============================
server.port=8080

# ===============================
# BLIZZARD API
# ===============================

blizzard.client-id=${BLIZZARD_CLIENT_ID}
blizzard.client-secret=${BLIZZARD_CLIENT_SECRET}
blizzard.region=us
blizzard.api-base-url=https://us.api.blizzard.com
blizzard.auth-base-url=https://oauth.battle.net
